version: '3.8'

services:
  # ---------------------------------------------------------
  # 1. IL DATABASE (Livello Stateful)
  # ---------------------------------------------------------
  mongodb:
    image: mongo:latest
    container_name: database_mongo
    ports:
      - "27017:27017"
    volumes:
      # Fondamentale: salviamo i dati del DB sul tuo disco per non perderli ai riavvii
      - dati_mongo:/data/db

  # ---------------------------------------------------------
  # 2. IL SERVER API (Livello Stateless)
  # ---------------------------------------------------------
  server_principale:
    build: ./Server_API
    container_name: api_centrale
    ports:
      - "5000:5000"
    depends_on:
      # Programmazione difensiva: accendi prima il DB, poi il server Python
      - mongodb
    environment:
      # Sicurezza: passiamo le variabili d'ambiente al container Python
      - SECRET_KEY=segreto_devops_123
      # DNS Interno: Diciamo al server Python di cercare Mongo non su 'localhost', ma sul nome del container 'mongodb'
      - MONGO_URI=mongodb://mongodb:27017/

volumes:
  # Dichiariamo il volume persistente per il database
  dati_mongo: